config/routes.rb
Rails.application.routes.draw do
  resources :users do
  end
  resources :subscriptions

  post '/' => 'subscriptions#index'
  post '/subscriptions/batch_create' => 'subscriptions#batch_create'

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
	belongs_to :user


end

app/models/user.rb
class User < ActiveRecord::Base
	validates :first_name, :last_name, :email, :password_hash, presence: true

	has_many :subscriptions

	include BCrypt

	def password
		@password ||= Password.new(password_hash)
	end

	def password=(new_password)
		@password = Password.create(new_password)
		self.password_hash = @password
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]
  # GET /subscriptions
  # GET /subscriptions.json
  def index
    # @user = User.find(session[:id])
    @subscriptions = Subscription.all
    @money = [0,0]
    @subscriptions.each do |s|
      @money[0] += s.price
    end
    @money[1] = (@money[0] - 79)*12 
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
    # format.json { render :json => @subscription }
    # respond_to :json
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
    @year_from_today = Date.today + 1.year
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to subscriptions_path, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  def batch_create

    array = params["ajax"].values
    puts "-============================"
    puts array
    array.each do |subscription_data|
      puts subscription_data
      Subscription.create!(subscription_data)
    end
    redirect_to "/subscriptions"
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_subscription
    @subscription = Subscription.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def subscription_params
    params.require(:subscription).permit(:name, :price, :exp_date, :pay_date, :tag)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :destroy]

	respond_to :html

	def index
		@user = User.new
		render :new
		# if session[:id] && User.find(session[:id])
		# 	render "subscriptions#index"
		# 	# render :login

		# else
		# 	# render subscriptions_path
		# 	@user = User.new

		# 	render :login
		# end
		# @users = User.all
		# respond_with(@users)
	end

	def show
		respond_with(@user)
	end

	def new
		@user = User.new
		respond_with(@user)
	end

	def edit
	end

	def create
		@user = User.new(user_params)
		@user.password = params[:password]
		if @user.save!
			session[:id] = @user.id
			redirect_to subscriptions_path
		else
			render :new
		end
	end

	def update
		@user.update(user_params)
		respond_with(@user)
	end

	def destroy
		@user.destroy
		respond_with(@user)
	end

	def login
		@user = User.find_by_email(params[:email])
		if @user.password == params[:password]
			session[:id] = @user.id
			# give_token
		else
			redirect_to home_url
		end
	end

	def logout
		session[:id] = nil
		redirect_to '/'
	end

	private
	def set_user
		@user = User.find(params[:id])
	end

	def user_params
		params.require(:user).permit(:first_name, :last_name, :address, :phone, :email, :password_hash)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def sortable(column, title = nil)
	  title ||= column.titleize
	  css_class = column == sort_column ? "current #{sort_direction}" : nil
	  direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
	  link_to title, {:sort => column, :direction => direction}, {:class => css_class}
	end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def current_user
		@current_user ||= User.find(id: session[:id])
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Subscribble</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'subscriptions' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="http://code.jboxcdn.com/0.3.2/jBox.min.js"></script>
    <script src="http://code.jboxcdn.com/0.3.2/jBox.min.js"></script>
    <link href="http://code.jboxcdn.com/0.3.2/jBox.css" rel="stylesheet">
    <script src="http://fgnass.github.io/spin.js/spin.min.js"></script>
    <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
  </head>
  <body>
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">
            <!-- <%=image_tag "subscribble.png"%> -->
          </a>
        </div>
        <a href="http://www.subscribble.co"><button type="button" class="btn btn-default navbar-btn pull-right">Sign Out
            <i class="glyphicon glyphicon-off"></i></button></a>
        <a href="http://www.subscribble.co"><button type="button" class="btn btn-default navbar-btn pull-right">Settings
            <i class="glyphicon glyphicon-cog"></i></button></a>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/subscriptions/_form.html.erb
<%= form_for(@subscription) do |f| %>
  <% if @subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% @subscription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type_of_subscription %><br>
    <%= f.check_box :monthly %> Monthly 
    <%= f.check_box :annual %> Annual 
  </div>
  <br>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :expires_on %><br>
    <%= f.date_select :exp_date, :value => @year_from_today %>
  </div>
  <div class="field">
    <%= f.label :payment_date %><br>
    <%= f.date_select :pay_date %>
  </div>
  <div class="field">
    <%= f.label :tag %><br>
    <select name="subscription[tag]">
  <option></option>
<i class="glyphicon glyphicon-film"></i>
  <option>Movies</option>
  <option>Music</option>
  <option>Phone</option>
  <option>Fitness</option>

</select>
  </div>
  <br>
  <div class="actions">
    <td><button class="btn btn-success" id="destroy"><i class="glyphicon glyphicon-plus-sign"></i><% f.submit %> Save Changes</button></td>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<div class="centered">
<h1>Editing subscription</h1>
	<%= render 'form' %>  
<td><a href=<%= subscriptions_path %>><button class="btn btn-primary" id="destroy"><i class="glyphicon glyphicon-arrow-left"></i> Back</button></a></td>
	        
</div>
<br>


<!-- <td><a href=<%= @subscription %>><button class="btn btn-primary" id="destroy"><i class="glyphicon glyphicon-search"></i> Show</button></a></td> -->

app/views/subscriptions/index.html.erb
<div class="page-header">
  <h1>
    <%= image_tag "unnamed.png", size: "45" %>ubscribble
    <small>Save Time, Save Money, Save Hassle</small></h1>
</div>

<input type="button" id="import-gmail" data-confirm="The Application Subscribble is requesting permission to access your Google Account" value="Import Subscriptions from Email" />
<h3>Your Subscriptions</h3>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Next Payment Due</th>
      <th>Expires</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody id="main">
    <% tag_hash = { "Movies" => "glyphicon-film", "Music" => "glyphicon-music", "Phone"=> "glyphicon-phone" ,"Shopping" => "glyphicon-shopping-cart", "Fitness" => "glyphicon-user", "Print" => "glyphicon-book" }%>
    <% @subscriptions.each do |subscription| %>
      <tr class="<%= subscription.tag %>">
        <td>
          <i class="glyphicon <%= tag_hash[subscription.tag] %>"></i>
          <%= subscription.name %></td>
        <td>$<%= subscription.price %><small><% unless subscription.monthly %>/mo<% else %>/yr<%end%></small></td>
        <td><%= subscription.pay_date.to_formatted_s(:long_ordinal)[0..-7] %></td>
        <td><%= subscription.exp_date.to_formatted_s(:long_ordinal) %></td>
        <td><a href=<%= subscription_path(subscription) %>><button class="btn btn-primary" id="destroy">
              <i class="glyphicon glyphicon-search"></i>
              Details</button></a>
        </td>
        <td><a href=<%=edit_subscription_path(subscription) %>><button class="btn btn-primary" id="destroy">
              <i class="glyphicon glyphicon-pencil"></i>
              Edit</button></a>
        </td>
        <td><a href=<%=subscription.url %>><button class="btn btn-danger" id="destroy">
              <i class="glyphicon glyphicon-trash"></i>
              Unsubscribe</button></a>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<a href=<%= new_subscription_path %>><button class="btn btn-success" id="destroy">
    <i class="glyphicon glyphicon-plus-sign"></i>
    Add a Subscription</button></a>
<hr>
<br>
<h3>Your Spending</h3>
<hr>
<% unless @subscriptions.empty? %>
<h4>Your total cost for subscriptions this month is <strong>$<%= @money[0] %></strong>.</h4>
<h4>Your annual subscription cost is <strong>$<%= @money[1] %></strong>.</p>
<br>
<%else%>
<p>Add some subscriptions to see statistics here.</p>
<% end %>
<div>
  <canvas id="myChart" width="400" height="400"></canvas>
</div>
<br>

app/views/subscriptions/new.html.erb
<div class="page-header">
  <h1>
    <%= image_tag "unnamed.png", size: "45" %>ubscribble
    <small>Save Time, Save Money, Save Hassle</small></h1>
</div>

<div class="centered">

<h1>New subscription</h1>

<%= render 'form' %>

<td><a href=<%= subscriptions_path %>><button class="btn btn-primary" id="destroy"><i class="glyphicon glyphicon-arrow-left"></i> Back</button></a></td>

</div>

app/views/subscriptions/show.html.erb
<div class="centered">

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subscription.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @subscription.price %>
</p>

<p>
  <strong>Expiration date:</strong>
  <%= @subscription.exp_date %>
</p>

<p>
  <strong>Payment date:</strong>
  <%= @subscription.pay_date %>
</p>

<td><a href=<%= subscriptions_path %>><button class="btn btn-primary" id="destroy"><i class="glyphicon glyphicon-arrow-left"></i> Back</button></a></td>

<td><a href=<%=edit_subscription_path(@subscription) %>><button class="btn btn-primary" id="destroy">
                <i class="glyphicon glyphicon-pencil"></i> Edit</button></a>
        </td>

</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<form class="form-horizontal">
  <div>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.text_field :password_hash %>
  </div>
  <div class="actions">
    <br>
    <td><button class="btn btn-success" id="destroy"><i class="glyphicon glyphicon-plus-sign"></i><% f.submit %> Create Account</button></td>
      </div>
</form>

<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.address %></td>
        <td><%= user.phone %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/login.html.erb
<h1>Log In</h1>

<%= form_for @user, url: {action: "login"} do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="field">
  <%= f.label :email %><br>
  <%= f.text_field :email %>
</div>
<div class="field">
  <%= f.label :password_hash %><br>
  <%= f.text_field :password_hash %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/users/new.html.erb
	<div class="row">
            <%= image_tag "Logo-Subscribble-Green.png", size: "50%" %>
    </div>
    <div class="row">
        <div class="page-header">
            <h1>Less Time. More Savings. No Hassle.<small>  Organize your subscriptions.</small></h1>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-8">
            <div class="jumbotron">
                <h1>What is Subscribble?</h1>
                <h2>One subscription to rule them all.</h2>
                <footer><em></em><footer>
            </div>
            </div>

        <div class="col-sm-4">
            <div class="row centered-form">
                <div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">Sign up with us. <small>It's free!</small></h3>
                        </div>
                        <div class="panel-body">
                            <form role="form">
                                <div class="row">
                                    <div class="col-xs-6 col-sm-6 col-md-6">
                                        <div class="form-group">
                                            <input type="text" name="first_name" id="first_name" class="form-control input-sm" placeholder="First Name">
                                        </div>
                                    </div>
                                    <div class="col-xs-6 col-sm-6 col-md-6">
                                        <div class="form-group">
                                            <input type="text" name="last_name" id="last_name" class="form-control input-sm" placeholder="Last Name">
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <input type="email" name="email" id="email" class="form-control input-sm" placeholder="Email Address">
                                </div>

                                <div class="row">
                                    <div class="col-xs-6 col-sm-6 col-md-6">
                                        <div class="form-group">
                                            <input type="password" name="password" id="password" class="form-control input-sm" placeholder="Password">
                                        </div>
                                    </div>
                                    <div class="col-xs-6 col-sm-6 col-md-6">
                                        <div class="form-group">
                                            <input type="password" name="password_confirmation" id="password_confirmation" class="form-control input-sm" placeholder="Confirm Password">
                                        </div>
                                    </div>
                                </div>

                                <a href="/subscriptions"><input type="submit" value="Register" class="btn btn-block" style="background-color:#006a2c!important; color:White;" ></a>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
            </form>
        </div>
    </div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>